version: "3.8"

services:  
  go-application:
    container_name: miniprojectcontainer
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=Mbahbambang123
      - DB_DB=miniproject
      - DB_HOST=miniproject.ck6i8ucy7zfd.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
    # restart: on-failure